blog/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('blog.views',
    url(r'^preview$', 'preview'),
    url(r'^regulamin/$', 'statute', name='statute'),
    url(r'^rejestracja/$', 'registration', name='registration'),
    url(r'^logout/$', 'logout_page'),
    url(r'^send_photo$', 'load_photo'),
    url(r'^delete_entry/(?P<blog_entry_id>[\d]+)$', 'delete_entry', name='delete_entry'),
    url(r'^$', 'blogs', name='blogs'),
    url(r'^dodaj_blog$', 'add_blog', name='add_blog'),
    url(r'^(?P<blog_slug>[\w-]+)/konfiguracja_bloga$', 'configure_blog',
        {'is_edited': False}, name='configure_blog'),
    url(r'^(?P<blog_slug>[\w-]+)/edycja_bloga$', 'configure_blog',
        {'is_edited': True}, name='edit_blog'),
    url(r'^(?P<blog_slug>[\w-]+)/dodaj_wpis$', 'add_blog_entry',
        name='add_blog_entry'),
    url(r'^(?P<blog_slug>[\w-]+)/(?P<blog_entry_id>[\d]+)-'
        r'(?P<blog_entry_slug>[\w-]+)/edytuj_wpis$',
        'edit_blog_entry', name='edit_blog_entry'),
    url(r'^(?P<blog_slug>[\w-]+)$', 'main_blog_page', name='blog'),
    url(r'^(?P<blog_slug>[\w-]+)/(?P<blog_entry_id>[\d]+)-'
        r'(?P<blog_entry_slug>[\w-]+)$', 'blog_entry', name='blog_entry'),
)

blogowy_projekt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login

from blog import urls as blog_urls
from . import settings

urlpatterns = [
    url(r'^accounts/login/$', login, name='login'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(blog_urls)),

]

blog/models.py
#!/usr/bin/env python
# encoding: utf-8

from jsonfield.fields import JSONField

from django.contrib.auth.models import User
from django.db import models

from .enums import blog_entry_states, moderation_states


class Blog(models.Model):
    name = models.CharField(max_length=200)
    bloger = models.ForeignKey(User)
    slug = models.CharField(max_length=200, unique=True)

    avatar_url = models.CharField(max_length=200)
    headline_picture_url = models.CharField(max_length=200)

    description = models.TextField(null=True, blank=True)

    is_active = models.BooleanField(default=True)
    status = models.IntegerField(default=moderation_states.private)
    is_recommended = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class BlogEntry(models.Model):
    blog = models.ForeignKey(Blog)

    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    summary = models.CharField(max_length=1000)
    first_picture_url = models.CharField(null=True, blank=True, max_length=200)
    pictures_json = JSONField(default=[], null=True, blank=True)

    body = models.TextField()
    markdown_body = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    is_active = models.BooleanField(default=True)
    is_recommended = models.BooleanField(default=False)
    status = models.IntegerField(default=blog_entry_states.published)

    comments_allowed = models.BooleanField(default=True)
    visited = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Blog Entries'

    def __unicode__(self):
        return self.title


class Photo(models.Model):
    picture = models.ImageField(upload_to='/var/www/blog/photos/')

    def get_name(self):
        return str(self.picture).split('/')[-1]

    def __unicode__(self):
        return self.get_name()


class Comments(models.Model):
    blog_entry = models.ForeignKey(BlogEntry)
    author = models.CharField(max_length=200)

    created_at = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    status = models.IntegerField(default=blog_entry_states.published)

blog/views.py
#!/usr/bin/env python
# encoding: utf-8

from __future__ import absolute_import

import json
import markdown2

from annoying.decorators import render_to, ajax_request
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404, redirect

from .enums import blog_entry_states, moderation_states
from .forms import AddBlogForm, ConfigureBlogForm, EditBlogEntryForm, \
    AddBlogEntryForm, CommentForm, UserForm
from .helpers import UserPermissions, get_key
from .models import Blog, BlogEntry, Photo, Comments

from blogowy_projekt.settings import MAX_BLOGS_ON_PAGE, \
    MAX_BLOG_ENTRIES_ON_PAGE


def logout_page(request):
    logout(request)
    return redirect('/')


def registration(request):
    user_form = UserForm(data=request.POST or None)
    if request.method == 'POST':
        password = request.POST['password']
        repeated_password = request.POST['password_2']
        if password == repeated_password:
            if user_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                user = authenticate(username=user.username, password=password)
                login(request, user)
                return redirect('/')
    return redirect('login')


@render_to('statute.html')
def statute(request):
    return {}


@render_to('blogs.html')
def blogs(request):
    # get blog entries
    blog_entries = BlogEntry.objects.only(
        'blog', 'slug', 'title', 'first_picture_url', 'summary',)\
        .filter(is_active=True, status=blog_entry_states.published,
                blog__status=moderation_states.accepted,
                blog__is_active=True).order_by('-created_at')

    # get most popular
    most_popular = BlogEntry.objects.only(
        'blog', 'slug', 'title', 'first_picture_url', 'summary',)\
        .filter(is_active=True, status=blog_entry_states.published,
                blog__status=moderation_states.accepted,
                blog__is_active=True).order_by('-visited')[:3]

    # paginate blogs entries
    page_number = request.GET.get('strona', 1)
    pagination_page = get_paginated_page(blog_entries, MAX_BLOG_ENTRIES_ON_PAGE,
                                         page_number)
    blog_entries = pagination_page.object_list

    # get blogs
    blogs = Blog.objects.only('name', 'slug',)\
        .filter(is_active=True, status=moderation_states.accepted)\
        .order_by('name')

    blogs_data = sorted([(blog.name, blog.slug) for blog in blogs], key=get_key)

    return {
        'blog_entries': blog_entries,
        'pagination_page': pagination_page,
        'blogs_data': json.dumps(blogs_data),
        'max_blogs_on_page': MAX_BLOGS_ON_PAGE,
        'most_popular': most_popular,
    }


@render_to('main_blog_page.html')
def main_blog_page(request, blog_slug):
    blog = get_object_or_404(Blog, slug=blog_slug)

    user_permissions = UserPermissions(request.user, blog)
    if not user_permissions.can_show_main_blog_page:
        raise Http404()

    blog_entries = BlogEntry.objects.only(
        'first_picture_url', 'summary', 'slug', 'status', 'title')\
        .filter(blog=blog.id).order_by('-created_at')

    if not user_permissions.is_blog_owner:
        blog_entries = blog_entries.filter(status=blog_entry_states.published,
                                           is_active=True)

    # paginate blog entries
    page_number = request.GET.get('strona', 1)
    pagination_page = get_paginated_page(blog_entries, MAX_BLOG_ENTRIES_ON_PAGE,
                                         page_number)
    blog_entries = pagination_page.object_list

    return {
        'blog': blog,
        'blog_entries': blog_entries,
        'pagination_page': pagination_page,
        'moderation_states': moderation_states,
        'blog_entry_states': blog_entry_states,
        'user_permissions': user_permissions,
    }


@render_to('blog_entry.html')
def blog_entry(request, blog_slug, blog_entry_id, blog_entry_slug):
    blog_entry = get_object_or_404(BlogEntry, id=blog_entry_id)

    if blog_entry.slug != blog_entry_slug \
            or blog_entry.blog.slug != blog_slug:
        return redirect('blog_entry', blog_slug=blog_entry.blog.slug,
                        blog_entry_id=blog_entry_id,
                        blog_entry_slug=blog_entry.slug)

    user_permissions = UserPermissions(request.user, blog_entry.blog,
                                       blog_entry)
    if not user_permissions.can_show_blog_entry:
        raise Http404()

    if request.user != blog_entry.blog.bloger:
        blog_entry.visited += 1
        blog_entry.save()

    comment_entry_form = CommentForm(request.POST or None,
                                     blog_entry=blog_entry,
                                     user=request.user)
    if comment_entry_form.is_valid():
        comment_entry_form.save()

    comments = Comments.objects.filter(blog_entry_id=blog_entry_id)

    pictures = []
    for picture_object in blog_entry.pictures_json:
        url = picture_object['url']
        title = picture_object['title']
        pictures.append((url, title))

    related = BlogEntry.objects.only(
        'blog', 'slug', 'title', 'first_picture_url', 'summary',)\
        .filter(is_active=True, status=blog_entry_states.published,
                blog__status=moderation_states.accepted,
                blog__is_active=True).order_by('-visited').exclude(
        id=blog_entry.id)

    return {
        'blog': blog_entry.blog,
        'blog_entry': blog_entry,
        'blog_entry_states': blog_entry_states,
        'user_permissions': user_permissions,
        'comments': comments,
        'form': comment_entry_form,
        'moderation_states': moderation_states,
        'pictures': pictures,
        'related': related,
    }


@render_to('new_blog.html')
def add_blog(request):
    blog = Blog.objects.filter(bloger_id=request.user.id).first()

    if blog:
        if blog.status == moderation_states.accepted and blog.is_active:
            return redirect('blog', blog_slug=blog.slug)

        return {
            'can_add_blog': False,
            'blog': blog,
            'moderation_states': moderation_states,
        }

    add_blog_form = AddBlogForm(request.POST or None, request=request)

    if add_blog_form.is_valid():
        blog = add_blog_form.save()
        return redirect('configure_blog', blog_slug=blog.slug)

    return {
        'add_blog_form': add_blog_form,
        'can_add_blog': True,
    }


@login_required
@render_to('configure_blog.html')
def configure_blog(request, blog_slug, is_edited):
    blog = get_object_or_404(Blog, slug=blog_slug)
    user_permissions = UserPermissions(request.user, blog)
    if not user_permissions.can_configure_blog:
        raise Http404

    configure_blog_form = ConfigureBlogForm(request.POST or None, instance=blog)

    if configure_blog_form.is_valid():
        blog = configure_blog_form.save()
        return redirect('blog', blog_slug=blog.slug)

    return {
        'is_edited': is_edited,
        'blog': blog,
        'configure_blog_form': configure_blog_form,
    }


@login_required
@render_to('add_blog_entry.html')
def add_blog_entry(request, blog_slug):
    blog = get_object_or_404(Blog, slug=blog_slug, bloger_id=request.user.id)
    user_permissions = UserPermissions(request.user, blog)
    if not user_permissions.can_add_entry:
        raise Http404

    add_entry_form = AddBlogEntryForm(request.POST or None, blog=blog)

    if add_entry_form.is_valid():
        blog_entry = add_entry_form.save()
        return redirect('blog_entry', blog_slug, blog_entry.id,
                        blog_entry.slug)

    last_blog_entry = BlogEntry.objects.only('id').last()

    return {
        'form': add_entry_form,
        'blog_entry_id': last_blog_entry.id + 1 if last_blog_entry else 1,
    }


@login_required
@render_to('add_blog_entry.html')
def edit_blog_entry(request, blog_slug, blog_entry_id, blog_entry_slug):
    blog_entry = get_object_or_404(BlogEntry, blog__bloger_id=request.user.id,
                                   blog__slug=blog_slug, id=blog_entry_id,
                                   is_active=True)

    user_permissions = UserPermissions(request.user, blog_entry.blog)
    if not user_permissions.can_add_entry and blog_entry.is_active:
        raise Http404

    edit_entry_form = EditBlogEntryForm(request.POST or None,
                                        instance=blog_entry)

    if edit_entry_form.is_valid():
        blog_entry = edit_entry_form.save()
        return redirect('blog_entry', blog_slug, blog_entry.id,
                        blog_entry.slug)

    return {
        'form': edit_entry_form,
        'is_edited': True,
        'first_picture_url': blog_entry.first_picture_url,
        'blog_entry_id': blog_entry.id
    }


@ajax_request
def load_photo(request):
    created_photo = None
    for photo in request.FILES.values():
        created_photo = Photo.objects.create(picture=photo)

    if created_photo:
        return {'info': 'sukces', 'name': created_photo.get_name()}
    else:
        return {'info': 'dupa'}


@ajax_request
def delete_entry(request, blog_entry_id):
    blog_entry = get_object_or_404(BlogEntry, blog__bloger_id=request.user.id,
                                   id=blog_entry_id,
                                   is_active=True)
    blog_entry.is_active=False
    blog_entry.save()


@ajax_request
def preview(request):
    markdown_text = request.POST.get('markdown_text', '')
    try:
        preview_body = markdown2.markdown(markdown_text)
        template_name = 'preview_template.html'
        context = {'preview_body': preview_body}

blog/templates/add_blog_entry.html
{% extends "base.html" %}

{% block styles %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/entries_box.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/page_decoration.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/blog_box.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/edit.css' %}" />
{% endblock %}

{% block content %}
	{% if is_edited %}
		<h2 class="mainTitle">Edycja wpisu</h2>
	{% else %}
		<h2 class="mainTitle">Dodaj wpis</h2>
	{% endif %}
	<div class="underlineTitle"></div>
	<div>
		<form method="post" class="js-form addForm" data-blog-entry-id={{ blog_entry_id }}>
			<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			<div>
				<div class="label">Tytuł</div>
				<input class="smallText" id="id_title" maxlength="200" name="title" type="text" value="{{ form.title.value|default_if_none:'' }}">
				{% for error in form.title.errors %}
					<span>{{ error }}</span>
				{% endfor %}
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div>
				<div class="label">Krótki opis</div>
				<textarea class="smallText" rows="4" id="id_summary" maxlength="400" name="summary">{{ form.summary.value|default_if_none:'' }}</textarea>
				{% for error in form.summary.errors %}
					<span>{{ error }}</span>
				{% endfor %}
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div class="js-markdown-body">
				<div class="label">Treść</div>
				<textarea class="smallText js-markdown-text" style="overflow: auto; resize:vertical;" cols="40" id="id_markdown_body" name="markdown_body" rows="20">{{ form.markdown_body.value|default_if_none:'' }}</textarea>
				{% for error in form.markdown_body.errors %}
					<span>{{ error }}</span>
				{% endfor %}
				<a class="js-show-preview commentSubmit" href="#">Podgląd</a>
			</div>

			<div class="mainEntryBody js-preview" style="display: none;">
				<a class="js-edit commentSubmit" href="#">Edytuj</a>
			</div>

			<div style="clear:both;"></div>
			<div class="underline"></div>

			<div>
				<div class="label">Dozwolone komentarze</div>
				<div class="commentCheckbox" >
					<input {% if form.comments_allowed.value %}checked="checked"{% endif %} id="id_comments_allowed" name="comments_allowed" type="checkbox">
				</div>
				{% for error in form.comments_allowed.errors %}
					<span>{{ error }}</span>
				{% endfor %}
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div>
				<div class="label">Multimedia</div>
				<input class="js-file-upload filesButton" type="file" multiple>
				<div style="clear:both;"></div>
				<div class="label" style="width: 100%;">Wczytaj zdjędia, a następnie przeciągnij w wybrane miejsce w tekście.</div>
				<div style="clear:both;"></div>
				<div class="js-picture-holder"></div>
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div style="display:none;">
				{{ form.first_picture_url }}
			</div>

			<div style="display:none;">
				{{ form.pictures_json }}
			</div>

			<div class="js-pictures">
				<button class="commentSubmit" type="submit">Zapisz</button>
			</div>
		</form>

	</div>
	{% load compress %}
	{% load staticfiles %}

	{% compress js %}
		<script type="text/coffeescript" src="{% static 'js/blogs/multimedia.coffee' %}"></script>
	{% endcompress %}

	{% if is_edited %}
		<script>
			loadPicture()
		</script>
	{% endif %}
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/base.css' %}" />
	{% block styles %}
	{% endblock %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
<body>
	<ul>
		<li><a href="{% url 'add_blog' %}">Mój blog</a></li>
		<li><a href="/">Najnowsze wpisy</a></li>
		<li><a href="{% url 'statute' %}">Regulamin</a></li>
		<li style="float: right;">
			{% if not request.user.is_authenticated %}
				<a href="{% url 'login' %}?next={{ request.path_info }}">Zaloguj się</a>
			{% else %}
				<a href="/logout/"> {{ request.user.username }}
					<img class="shutdownIcon" src="{% static 'icons/shutdown.png' %}" />
				</a>
			{% endif %}
		</li>
		{% block optionalMenu %}
		{% endblock %}
	</ul>

	<center>
		<div class="mainContainer">
			<div class="firstSeparate"><br></div>
			{% block content %}
			{% endblock %}
		</div>
	</center>

	<div class="footer">

	</div>
</body>
</html>

blog/templates/blog_entry.html
{% extends "base.html" %}

{% block styles %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/entries_box.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/page_decoration.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/blog_box.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/photos.css' %}" />
{% endblock %}

{% block title %}{{blog_entry.title}}{% endblock %}

{% block optionalMenu %}
	{% if user_permissions.can_add_entry and blog_entry.is_active %}
		<li>
			<a href="{% url 'edit_blog_entry' blog.slug blog_entry.id blog_entry.slug %}">Edytuj wpis</a>
		</li>
		<li>
			<a href="" class="js-archive_entry" data-blog-entry-id="{{ blog_entry.id }}">Archiwizuj wpis</a>
		</li>
	{% endif %}

{% endblock %}

{% block content %}

	<h2 class="mainTitle">{{ blog_entry.blog.name }}</h2>
	<div class="underlineTitle"></div>
	<div class="mainEntryBox">
		<div class="mainEntryTitle">{{ blog_entry.title }}</div>
		{% if blog_entry.first_picture_url %}
				<img src="/media/{{ blog_entry.first_picture_url }}" class="mainEntryPicture">
		{% endif %}
		<div style="margin-top: 15px;" class="commentDate">Utworzony: {{ blog_entry.created_at }}</div>
		<div style="clear:both;"></div>
		<div class="commentDate">Edytowany: {{ blog_entry.updated_at }}</div>
		<div style="clear:both;"></div>
		<div class="mainEntrySummary">{{ blog_entry.summary|linebreaksbr }}</div>
		<div class="mainEntryBody">{{ blog_entry.body|safe|linebreaks }}</div>
	</div>

	<div class="blogInformationContainer js-blog-information-container">
		<div class="smallTitle">Blog</div>

		<div class="blogInformation">
			{% if blog.status == moderation_states.private %}
				<div class="smallRejectedEntry">
					<div class="badBlogStatusText">Blog jeszcze nieaktywowany i widoczny tylko prywatnie</div>
				</div>
			{% elif blog.status == moderation_states.rejected or not blog.is_active %}
				<div class="smallArchiveEntry">
					<div class="badBlogStatusText">Blog zablokowany i widoczny tylko prywatnie.</div>
				</div>
			{% endif %}
			<div><img class="entryContainerPhoto" src="/media/{{ blog.headline_picture_url }}"></div>
			<img class="bloggerAvatar" src="/media/{{ blog.avatar_url }}">
			<div class="bloggerName">{{ blog.bloger.username }}</div>
			<div class="blogDescription" style="clear: both;">{{ blog.description }}</div>
		</div>
	</div>

	<div class="blogInformationContainer js-related-container" style="overflow: hidden;">
		<div class="smallTitle">Zobacz również</div>

		{% for blog_entry in related %}
			<div class="entryContainer" style="float: left;">
				<a href="{% url 'blog_entry' blog.slug blog_entry.id blog_entry.slug %}">
					{% if blog_entry.first_picture_url %}
						<img src="/media/{{ blog_entry.first_picture_url }}" class="entryContainerPhoto">
					{% endif %}
					<div class="entryContainerTitle" style="max-width:280px;">{{ blog_entry.title }}</div>
				</a>
				<div class="entryContainerSummary">{{ blog_entry.summary }}</div>
				<div class="entryContainerDate">{{ blog_entry.created_at }}</div>
			</div>
			{% endfor %}
	</div>

	<div class="separate"></div>

	{% if pictures %}
		<h2 class="mainTitle">Galeria</h2>
		<div class="underlineTitle"></div>
		<div class="photosBox">
			{% for url, title in pictures %}
				<a href="/media/{{ url }}">
					<img class="picture_icon" src="/media/{{ url }}">
				</a>
			{% endfor %}
		</div>
	{% endif %}

	<div class="separate"></div>

	{% if blog_entry.comments_allowed %}
		<div class="commentsContainer">
			<h2 class="mainTitle">Komentarze</h2>
			<div class="underlineTitle"></div>

			<div>
				<form method="post">
					<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
					<textarea class="commentTextArea" cols="40" id="id_body" name="body" rows="10"></textarea>
					{% for error in form.title.errors %}
						<span>{{ error }}</span>
					{% endfor %}
					<button class="commentSubmit" type="submit">Publikuj</button>
				</form>
			</div>

			{% for comment in comments %}
				<div class="commentBox">
					<div class="commentAuthor">{{ comment.author }}</div>
					<div class="commentDate">{{ comment.created_at }}</div>
					<div class="commentBody">{{ comment.body }}</div>
				</div>
			{% endfor %}
		</div>
	{% endif %}

	{% load compress %}
	{% load staticfiles %}

	{% compress js %}
		<script type="text/coffeescript" src="{% static 'js/blogs/archive_entry.coffee' %}"></script>
		<script type="text/coffeescript" src="{% static 'js/blogs/related.coffee' %}"></script>
	{% endcompress %}

{% endblock %}

blog/templates/configure_blog.html
{% extends "base.html" %}

{% block styles %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/entries_box.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/page_decoration.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/blog_box.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/blogs/edit.css' %}" />
{% endblock %}

{% block content %}
	<div>
		<h2 class="mainTitle">{% if is_edited %}Konfiguracja{% else %}Skonfiguruj pozostałe ustawienia{% endif %}</h2>
		<div class="underlineTitle"></div>

		<form method="post">
			<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			<div>
				<div class="label">Nazwa</div>
				{% if is_edited %}
				<input class="smallText" id="id_name" type="text" name="name" value="{{ configure_blog_form.name.value }}">
				{% else %}
					<div class="staticTextForm">{{ blog.name }}</div>
					<input class="smallText" id="id_name" type="hidden" name="name" value="{{ configure_blog_form.name.value }}">
				{% endif %}
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div>
				<div class="label">Slug </div>
				<div class="staticTextForm">{{ blog.slug }}</div>
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div>
				<div class="label">Opis</div>
				<textarea class="smallText" rows="4" id="id_description" type="text" name="description">{% if is_edited %}{{ configure_blog_form.description.value|default_if_none:'' }}{% endif %}</textarea>
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div>
				<div class="label">Avatar</div>
				<div>
					<div>
						<img class="js-avatar-picture-preview bloggerAvatar" src="/media/{{ configure_blog_form.avatar_url.value }}">
					</div>
					<div style="clear:both;"></div>
					<div class="label">Zmień</div>
					<input class="js-avatar-picture-input filesButton" type="file">
					<input id="id_avatar_url" type="hidden" class="js-new-avatar-picture-url" name="avatar_url" value="{{ configure_blog_form.avatar_url.value }}">
				</div>
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>

			<div>
				<div class="label">Grafika nagłówka</div>
				<div>
					<div>
						<img src="/media/{{ configure_blog_form.headline_picture_url.value }}" class="js-headline-picture-preview headlinePhoto">
					</div>
					<div style="clear:both;"></div>
					<div class="label">Zmień</div>
					<input class="js-headline-picture-input filesButton" type="file">
					<input id="id_headline_picture_url" type="hidden" class="js-new-headline-picture-url" name="headline_picture_url" value="{{ configure_blog_form.headline_picture_url.value }}">
				</div>
				<div style="clear:both;"></div>
			</div>

			<div class="underline"></div>
			<button type="submit" class="commentSubmit">Zapisz</button>
		</form>
	</div>

	{% load compress %}
	{% load staticfiles %}

	{% compress js %}
		<script type="text/coffeescript" src="{% static 'js/blogs/main_photos.coffee' %}"></script>
	{% endcompress %}

{% endblock %}

blog/templates/preview_template.html
<div class="mainEntryBody">{{ preview_body|safe|linebreaks }}</div>